<h1 style="border: 2px solid violet; border-radius: 8px; text-align: center; padding: 8px;" > Mathematics for data science </h1>


In [1]:
import numpy as np
from Mat import Mat

**1| `matMulCheck(A,B)`** to check if the product of two given matrices `A` and `B` is possible in a single line of code. Test it with a defined and an undefined case.

In [2]:
print(
    "Defined case: ",
    Mat.matMulCheck(
        np.array([[6, -5, -5, 8], [9, -3, 7, 7]]),
        np.array([[0, -7, -7, 6], [5, 3, -5, 2], [6, 6, 0, -4], [3, -5, 0, -10]]),
    ),
)
print(
    "Undefined case: ",
    Mat.matMulCheck(
        np.array([[6], [3], [1]]),
        np.array([[5, -3, -1, -6], [0, 5, -9, -7], [-2, -3, -6, 2], [-9, -4, 0, -6]]),
    ),
)

Defined case:  True
Undefined case:  False


**2| `matMul(A,B)`** to calculate the dot product of two given matrices only when possible (handle the error using `matMulCheck(A,B)`.) in maximum two lines of code and without using element wise multiplication.

In [3]:
print("Result:")
print(
    Mat.matMul(
        np.array([[6, -5, -5, 8], [9, -3, 7, 7]]),
        np.array([[0, -7, -7, 6], [5, 3, -5, 2], [6, 6, 0, -4], [3, -5, 0, -10]]),
    )
)
print("Expected result:")
print(
    np.dot(
        np.array([[6, -5, -5, 8], [9, -3, 7, 7]]),
        np.array([[0, -7, -7, 6], [5, 3, -5, 2], [6, 6, 0, -4], [3, -5, 0, -10]]),
    )
)

Result:
[[ -31 -127  -17  -34]
 [  48  -65  -48  -50]]
Expected result:
[[ -31 -127  -17  -34]
 [  48  -65  -48  -50]]


**3| `augmentedMat(A,b)`** to construct the augmented matrix in two different ways.

In [4]:
augmented_mat1, augmented_mat2 = Mat.augmentedMat(
    np.array([[1, 2], [3, 4], [5, 6]]), np.array([7, 8, 9])
)
print(augmented_mat1)
print("==============")
print(augmented_mat2)

[[1 2 7]
 [3 4 8]
 [5 6 9]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


**4| `solveLinearSystem(A,b)`** to solve a linear system of equations Ax = b given A and b then use `np.linalg.solve()` to check your solution.

In [5]:
print(
    "Result:",
    Mat.solveLinearSystem(
        np.array([[2, 1, -1], [4, -1, 3], [3, 5, -2]]), np.array([1, 2, 3])
    ),
)
print(
    "Expected result:",
    np.linalg.solve(
        np.array([[2, 1, -1], [4, -1, 3], [3, 5, -2]]), np.array([1, 2, 3])
    ),
)

Result: [0.40625 0.46875 0.28125]
Expected result: [0.40625 0.46875 0.28125]


**5| `isSubspace(S)`** to check if a given set of vectors `S` is a subspace of R<sup>3</sup> use the Gaussian elimination.

In [6]:
print("Defined case1: ", Mat.isSubspace(np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])))
print(
    "Undefined case: ",
    Mat.isSubspace(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])),
)

Defined case1:  True
Undefined case:  False


c:\Users\Djezzar Moncef\Desktop\moncef\random\study\MML1\tp\tp 02\Mat.py:46: RuntimeWarning: invalid value encountered in scalar divide
  factor = A[j, i] / A[i, i]


**6| `det(A)`** to calculate the determinant of a matrix and test it using `np.linalg.solve()`.


In [7]:
print("Result:", Mat.det(np.array([[2, 4, 3], [1, 3, 3], [3, 3, 3]])))
print("Expected result:", np.linalg.det(np.array([[2, 4, 3], [1, 3, 3], [3, 3, 3]])))

Result: 6
Expected result: 6.0
